### ISSUE TITLE
Support for EE10

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/liberty-arquillian#113]
##### Issue Overview

I'd like to test with still-under-development EE10 features, but the `arquillian-support-jakarta-2.0` feature depends on `servlet-5.0` and does not tolerate `6.0`;

##### Expected Behaviour

I'd like to fully support development in EE10.

##### Current Behaviour

So far, EE10 support in Liberty is limited by the feature.  It results in a feature manager conflict when using EE10 features like `restfulWS-3.1` that depend on `servlet-6.0` when the `arquillian-support-jakarta-2.0` features depends on `servlet-5.0`.

##### Steps To Reproduce
1. Start a server using a server.xml with both `arquillian-support-jakarta-2.0` and `restfulWS-3.1`.
2. Check the logs - startup will have failed due to feature conflict.

##### Additional Information

I'll plan to provide a PR that adds "6.0" to the tolerates list.

**Comment by brideck** [comment]
The Arquillian version also needs to be bumped to 1.7.Alpha10.  The Alpha9 version is still using a deprecated CDI API that has now been removed in EE 10.

**Comment by hantsy** [comment]
I tried to run the a simple test for Jakarta EE 10 JMSHello example against OpenLiberty 23.0.0.4, and got failure info like this:


```bash 
org.jboss.arquillian.container.spi.client.container.DeploymentException: Timeout while waiting for "test-4aa2d2ac-b700-43c0-affe-6ce560cae4bf" ApplicationMBean to reach STARTED. Actual state: STARTING.
	at 
```

The detailed exception stack on Github actions: https://github.com/hantsy/jakartaee10-starter-boilerplate/actions/runs/5163176246/jobs/9301347537

**Comment by cherylking** [comment]
@hantsy I think you should open a separate issue for the problem you are seeing. Also, I went through the GHA log you linked and found a lot of potential issues before the error it failed on. Have you gone through the whole log looking for application and configuration issues that could cause the failure?

Here are a few of the lines that caught my eye (null variables, missing files, user feature not found, keystore configuration problems) :

https://github.com/hantsy/jakartaee10-starter-boilerplate/actions/runs/5163176246/jobs/9301347537#step:4:15539

https://github.com/hantsy/jakartaee10-starter-boilerplate/actions/runs/5163176246/jobs/9301347537#step:4:15668

https://github.com/hantsy/jakartaee10-starter-boilerplate/actions/runs/5163176246/jobs/9301347537#step:4:15901

https://github.com/hantsy/jakartaee10-starter-boilerplate/actions/runs/5163176246/jobs/9301347537#step:4:16001

https://github.com/hantsy/jakartaee10-starter-boilerplate/actions/runs/5163176246/jobs/9301347537#step:4:16250

**Comment by jhanders34** [comment]
All issues should be resolved now to EE 10 support and tests are updated now to use released versions of both open liberty and websphere liberty with EE 10 support instead of beta versions.
