### ISSUE TITLE
Plugin not usable for JDK 9+

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/liberty-arquillian#13]
##### Issue Overview

As of Java 9 the tools jar at `JAVA_HOME/tools.jar` has been removed and converted to a module.  When running a project on JDK 9+ that includes the liberty-arquillian plugin, we get an error like this:

> [ERROR] Failed to execute goal on project tck.runner.tck: Could not resolve dependencies for project com.ibm.ws.microprofile.config:tck.runner.tck:jar:1.0-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.6.0 at specified path /home/java/openJ9_jdk10_20180611-sdk/../lib/tools.jar -> [Help 1]

##### Steps To Reproduce
1. Can run `mvn verify -Druntime=ol -DruntimeVersion=18.0.0.1` on this repo with JDK 9+

**Comment by gpoul** [comment]
Copying over this information from https://github.com/arquillian/arquillian-container-was/pull/33#issuecomment-377353115:

The only thing we use from the tools.jar is the Java Attach API; I think this might be useful, but it will require some investigation and testing: https://stackoverflow.com/questions/35240134/declare-maven-dependency-on-tools-jar-to-work-on-jdk-9

**Comment by aguibert** [comment]
Helps to support https://github.com/OpenLiberty/open-liberty/issues/540

**Comment by chyt** [comment]
Closed by #14.
