### ISSUE TITLE
Create nested set of Deployment/Definiton Exceptions from FFDC 'caused by' chain.

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/liberty-arquillian#6]
Issue to solve problem discussed here: 
http://lists.jboss.org/pipermail/weld-dev/2018-April/003664.html
(and here https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=253519)

Currently the container scrapes the message log to support ShouldThrow
Exceptions by creating a single 'cause' exception. 
Other containers (e.g. wildfly) support stacks of causal chain exceptions, 
for example as we see in out FFDC files and this enables them to pass tests
without individual tweeking for tests. 

The accepted practice (as implemented in the Arquillian Core) is to pass a
ShouldThrow if any of the causal chain of exceptions "is a" exception of
the correct type. So this is what we will want to feed it.

**Comment by chyt** [comment]
Closed by #7.
