### ISSUE TITLE
usr:arquillian-support-1.0 is not found

### ISSUE THREAD

**Issue by hantsy** [OpenLiberty/liberty-arquillian#65]
When I have add `usr:arquillian-support-1.0` feature to *server.xml* and start the application server and got the error info like this.

```bash
[ERROR   ] CWWKF0001E: A feature definition could not be found for usr:arquillian-support-1.0
```

**Comment by chyt** [comment]
As indicated in the issue template, please use StackOverflow for questions on how to use something, or why something isn't working.

**Comment by hantsy** [comment]
Asked a question on stackoverflow, https://stackoverflow.com/questions/60162005/a-feature-definition-could-not-be-found-for-usrarquillian-support-1-0
