### ISSUE TITLE
liberty-remote's `README.md` references unavailable feature

### ISSUE THREAD

**Issue by rslemos** [OpenLiberty/liberty-arquillian#99]
In [liberty-remote's `README.md`](https://github.com/OpenLiberty/liberty-arquillian/blob/master/liberty-remote/README.md#prerequisites), the developer is asked to add feature `restConnector-1.0`, which is not available for open liberty.

**Comment by cherylking** [comment]
I think the documentation just needs to be updated to require `restConnector-2.0` feature. Does it work for you if you add that feature instead?

**Comment by rslemos** [comment]
I've updated to `restConnector-2.0`, but I'm still having many many problems. It will take a long time before I can tell if it is indeed working.

**Comment by rslemos** [comment]
As matter of fact, https://github.com/OpenLiberty/liberty-arquillian/blob/arquillian-parent-liberty-1.0.6/liberty-remote/src/test/resources/server.xml uses `restConnector-2.0`. So, it seems to be just a bug in documentation.
